// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyWPybw9FbLD9eE6iUtEljiF7KM3uQZRQ',
    appId: '1:345513554721:web:06ca40600281f734580460',
    messagingSenderId: '345513554721',
    projectId: 'first-flutter-app-5bdb9',
    authDomain: 'first-flutter-app-5bdb9.firebaseapp.com',
    storageBucket: 'first-flutter-app-5bdb9.firebasestorage.app',
    measurementId: 'G-DF3K4NPSYC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoqImZSkd_r6lQMbS9v3cI9GDAj8_Iwp0',
    appId: '1:345513554721:android:33f5a5df5a7ba9be580460',
    messagingSenderId: '345513554721',
    projectId: 'first-flutter-app-5bdb9',
    storageBucket: 'first-flutter-app-5bdb9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSHeEMboz5in2QJOh1Ocg73PdHqaBqqyQ',
    appId: '1:345513554721:ios:02749fd4dbfd5cae580460',
    messagingSenderId: '345513554721',
    projectId: 'first-flutter-app-5bdb9',
    storageBucket: 'first-flutter-app-5bdb9.firebasestorage.app',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSHeEMboz5in2QJOh1Ocg73PdHqaBqqyQ',
    appId: '1:345513554721:ios:02749fd4dbfd5cae580460',
    messagingSenderId: '345513554721',
    projectId: 'first-flutter-app-5bdb9',
    storageBucket: 'first-flutter-app-5bdb9.firebasestorage.app',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDyWPybw9FbLD9eE6iUtEljiF7KM3uQZRQ',
    appId: '1:345513554721:web:3cdc409d98f58cc0580460',
    messagingSenderId: '345513554721',
    projectId: 'first-flutter-app-5bdb9',
    authDomain: 'first-flutter-app-5bdb9.firebaseapp.com',
    storageBucket: 'first-flutter-app-5bdb9.firebasestorage.app',
    measurementId: 'G-MQKMPET0MC',
  );
}
